services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '${DB_USERNAME:-kai}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD:-notsecure}'
      WORDPRESS_DB_NAME: '${DB_DATABASE:-database}'
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      # plugins:/var/www/html/wp-content/plugins
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-notsecure}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-database}'
      MYSQL_USER: '${DB_USERNAME:-kai}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-notsecure}'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
        test:
          - CMD
          - mysqladmin
          - ping
          - '-p${DB_PASSWORD:-notsecure}'
        retries: 3
        timeout: 5s

volumes:
  wordpress:
  db:
